name: lockin
description: 'Your Personal Habit & Productivity Companion'
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

version: 1.0.0-beta.5+5

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # Core dependencies
  dynamic_color: ^1.8.1
  fl_chart: ^1.1.1
  flutter_local_notifications: ^19.5.0
  flutter_riverpod: ^2.6.1
  hive_ce: ^2.19.0
  hive_ce_flutter: ^2.3.4
  path_provider: ^2.1.3
  intl: ^0.20.2
  encrypt: ^5.0.3
  timezone: ^0.10.1
  workmanager: ^0.9.0+3
  permission_handler: ^12.0.1
  file_picker: ^10.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # For code generation
  hive_ce_generator: ^1.11.0
  build_runner: ^2.10.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/Lato/Lato-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Lato/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato/Lato-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Lato/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato/Lato-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Lato/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato/Lato-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Lato/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/Lato/Lato-ThinItalic.ttf
          weight: 100
          style: italic
